CREATE DATABASE IF NOT EXISTS mysqldb;

-- USE mysqldb;

-- CREATE TABLE IF NOT EXISTS users (
--   id INT AUTO_INCREMENT PRIMARY KEY,
--   username VARCHAR(255) UNIQUE,
--   password VARCHAR(255)
-- );
