name: Run test and deploy to docker image to ECS

# Trigger the workflow when pushing to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql-test:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root123 # Set the root password
          MYSQL_DATABASE: mysqldb
        ports:
          - "3306:3306"
        options:
          --health-cmd="mysqladmin ping --host=localhost --user=root --password=root123"
          --health-timeout=5s
          --health-retries=10
          --health-start-period=30s

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Check MySQL container existence
        run: docker ps -a

      - name: Get MySQL container ID
        run: |
          CONTAINER_ID=$(docker ps -q --filter "ancestor=mysql:latest")
          echo "MySQL Container ID: $CONTAINER_ID"
          docker logs $CONTAINER_ID

      # Ensure MySQL is ready before running tests
      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          until mysqladmin ping --host=mysql-test --port=3306 --user=root --password=root123; do
            echo "Waiting for MySQL..."
            sleep 5
          done
          echo "MySQL is ready!"

      - name: Run tests
        run: npm test:pipe
